language: r

before_script:
  - cd /tmp && wget https://www-eu.apache.org/dist/spark/spark-2.3.3/spark-2.3.3-bin-hadoop2.7.tgz
  - cd /tmp && tar zxfv spark-2.3.3-bin-hadoop2.7.tgz

env:
  - SPARK_HOME=/tmp/spark-2.3.3-bin-hadoop2.7