language: r

before_install:
  - pushd . && cd /tmp && wget https://www-eu.apache.org/dist/spark/spark-2.3.3/spark-2.3.3-bin-hadoop2.7.tgz && tar zxfv spark-2.3.3-bin-hadoop2.7.tgz && popd

env:
  - SPARK_HOME=/tmp/spark-2.3.3-bin-hadoop2.7